### ISSUE TITLE
Rainbow Mode Not Working?

### ISSUE THREAD

**Issue by kleineluka** [zakudriver/nyan-mode-vscode#1]
Hi! I love this cute little plugin! But sadly, it seems like rainbow mode does not work. Any fixes? (On MacOS, latest VSCode)

**Comment by zakudriver** [comment]
Thank you for your feedback. 

Can you provide more clues? Maybe you can look up some errors at "help - Toggle Developer Tools".
I run it without any problems on MacOS and Win10 (Version: 1.78.1). 😅

**Comment by kleineluka** [comment]
Hmm. I don't see anything in the developer tools that would indicate Nyan Mode is erroring , and since it works on multiple operating systems for you, I'll assume this is probably just some weird extension conflict or issue with my theme / workspace that is causing the issue. I'll close this now and continue debugging on my own, but I appreciate your swift response!
